# This is a basic workflow to help you get started with Actions

name: Build flatpak bundle

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        dnf install -y quilt
    - name: Apply patches
      run: |
        quilt push
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: SDRangel.flatpak
        manifest-path: sdrangel/flatpak/org.sdrangel.SDRangel.json
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: SDRangel.flatpak
